### ISSUE TITLE
Support projects with *.spec.in suffix

### ISSUE THREAD

**Issue by jkonecny12** [vojtechtrefny/copr-builder#27]
In [Anaconda](https://github.com/rhinstaller/anaconda/blob/master/anaconda.spec.in) we are using autotools which is doing its black magic with the spec file. It would be nice for example, to support running autotools before reading these values. Or even better have something like pre-setup section in configuration file of copr-builder.

**Comment by vojtechtrefny** [comment]
Fixed in #28
